# Generated by Django 5.0.6 on 2024-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descb', models.CharField(max_length=200)),
                ('descl', models.CharField(max_length=200, null=True)),
                ('images', models.ImageField(null=True, upload_to='images/')),
                ('meta', models.IntegerField()),
                ('recolectado', models.IntegerField()),
                ('donadores', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.CharField(max_length=200, verbose_name='engagement')),
                ('compartidos', models.CharField(max_length=200, verbose_name='compartidos')),
                ('obj', models.CharField(max_length=200, verbose_name='Recaudo objetivo')),
                ('rec', models.CharField(max_length=200, verbose_name='Recaudo')),
                ('visitantes', models.CharField(max_length=200, verbose_name='Visitantes nuevos')),
            ],
        ),
        migrations.CreateModel(
            name='TextosBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
            ],
        ),
    ]
