# Generated by Django 5.0.6 on 2024-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='beneficiados',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='casos',
            name='imagesbanner',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='casos',
            name='ubicacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
