# Generated by Django 5.0.6 on 2024-06-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0003_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='nombre',
        ),
    ]
