# Generated by Django 5.0.6 on 2024-06-14 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0004_remove_adminuser_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casos',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufqaweb.casos')),
            ],
        ),
    ]
