# Generated by Django 5.0.6 on 2024-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0009_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='update',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
