# Generated by Django 5.0.6 on 2024-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0011_casos_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='accBank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='accNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casos',
            name='directDonation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
