# Generated by Django 5.0.6 on 2024-06-24 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufqaweb', '0012_casos_accbank_casos_accnumber_casos_directdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casos',
            name='donadores',
        ),
        migrations.CreateModel(
            name='Donadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donatorName', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufqaweb.casos')),
            ],
        ),
    ]
